defaults: &defaults
  docker:
    - image: circleci/node:11.5.0

version: 2
jobs:
    semver:
        <<: *defaults
        steps:
        - checkout
        - restore_cache:
            key: dependency-cache-{{ checksum "package.json" }}
        - run:
            name: Install npm
            command: npm ci
        # - run:
        #     name: Semantic Release
        #     command: node_modules/.bin/semantic-release

workflows:
  version: 2
  build_test_release:
    jobs:
      - build
      - semver:
          requires:
            - build
        #   filters:
        #     branches:
        #       only: master